# Generated by Django 4.2 on 2023-04-05 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'aliases',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Citation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cite_key', models.TextField()),
                ('pos', models.TextField()),
                ('properties', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'citations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Files',
            fields=[
                ('file', models.TextField(blank=True, primary_key=True, serialize=False)),
                ('title', models.TextField(blank=True, null=True)),
                ('hash', models.TextField()),
                ('atime', models.TextField()),
                ('mtime', models.TextField()),
            ],
            options={
                'db_table': 'files',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Links',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pos', models.TextField()),
                ('dest', models.TextField()),
                ('type', models.TextField()),
                ('properties', models.TextField()),
            ],
            options={
                'db_table': 'links',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('level', models.TextField()),
                ('pos', models.TextField()),
                ('todo', models.TextField(blank=True, null=True)),
                ('priority', models.TextField(blank=True, null=True)),
                ('scheduled', models.TextField(blank=True, null=True)),
                ('deadline', models.TextField(blank=True, null=True)),
                ('title', models.TextField(blank=True, null=True)),
                ('properties', models.TextField(blank=True, null=True)),
                ('olp', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'nodes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Refs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.TextField()),
                ('type', models.TextField()),
            ],
            options={
                'db_table': 'refs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tags',
                'managed': False,
            },
        ),
    ]
